module.exports = {
    PREFIX: ".",
    logChannel: "815335004589785160",
    welcomeChannel: "780967478301294623",
    goodbayChannel: "782260598867361812",

    intents: ["GUILDS","GUILD_MESSAGES","DIRECT_MESSAGES","GUILD_BANS","GUILD_EMOJIS_AND_STICKERS","GUILD_INTEGRATIONS","GUILD_WEBHOOKS","GUILD_INVITES","GUILD_VOICE_STATES","GUILD_MESSAGE_REACTIONS","GUILD_MESSAGE_TYPING","DIRECT_MESSAGE_REACTIONS","DIRECT_MESSAGE_TYPING","GUILD_PRESENCES","GUILD_MEMBERS", "DIRECT_MESSAGES"],
    partials: ["USER","CHANNEL","GUILD_MEMBER","MESSAGE","REACTION"]
};